<?php
declare(strict_types=1);

/**
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

namespace Ytake\TrinoClient;

/**
 * Class TrinoHeaders
 *
 * @author Yuuki Takezawa <yuuki.takezawa@comnect.jp.net>
 */
final class TrinoHeaders
{
    const TRINO_USER = "X-Trino-User";
    const TRINO_SOURCE = "X-Trino-Source";
    const TRINO_CATALOG = "X-Trino-Catalog";
    const TRINO_SCHEMA = "X-Trino-Schema";
    const TRINO_SESSION = "X-Trino-Session";
    const TRINO_PREPARED_STATEMENT = "X-Trino-Prepared-Statement";
    const TRINO_TRANSACTION_ID = "X-Presto-Transaction-Id";

    /** library version */
    const VERSION = '0.1.0';
    const TRINO_SOURCE_VALUE = 'TrinoClient';

    private function __construct()
    {
        //
    }
}
